apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./podinfo-0.3.3.tgz
      version: '0.3.3'
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: default
      interval: 1m
