apiVersion: v1
version: 0.3.3
appVersion: 0.3.3
name: podinfo
engine: gotpl
description: Podinfo Helm chart for Kubernetes
home: https://github.com/stefanprodan/podinfo
maintainers:
- email: stefanprodan@users.noreply.github.com
  name: stefanprodan
sources:
- https://github.com/Sahaquielxo/podinfo
kubeVersion: ">=1.23.0-0"
